sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dockerhubdxtat/lrn-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dockerhubdxtat/lrn-react-test npm test

after_success:
  - docker build -t dockerhubdxtat/lrn-multi-client ./client
  - docker build -t dockerhubdxtat/lrn-multi-nginx ./nginx
  - docker build -t dockerhubdxtat/lrn-multi-server ./server
  - docker build -t dockerhubdxtat/lrn-multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u dockerhubdxtat --password-stdin
  - docker push dockerhubdxtat/lrn-multi-client
  - docker push dockerhubdxtat/lrn-multi-nginx
  - docker push dockerhubdxtat/lrn-multi-server
  - docker push dockerhubdxtat/lrn-multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "lrn-multi-docker"
  env: "Lrn-multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-567504720652"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
